[package]
name = "cv"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
askama = "0.14.0"
im = { version = "15.1", features = ["serde"] }
anyhow = "1.0"
reqwest = { version = "0.12.15", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
