[package]
name = "cv"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
reqwest = { version = "0.12.18", features = ["json", "blocking"] }
hostname = "0.4.1"
flate2 = "1.1.1"
regex = "1.11.1"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.98"
dirs = "6.0.0"
chrono = { version = "0.4.41", features = ["serde"] }
axum = { version = "0.8.4", features = ["json", "macros"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
whoami = "2.0.0-pre.2"
keyring = "3.6.2"
git2 = "0.20.2"
minify-html = "0.16.4"
im = { version = "15.1", features = ["serde"] }
tower-http = { version = "0.6.6", features = ["fs", "cors", "timeout"] }
askama = "0.14.0"
thiserror = "2.0.12"
r2d2 = "0.8.10"
r2d2_sqlite = "0.31.0"
tempfile = "3.10.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
tracing-appender = "0.2.3"
tracing-log = "0.2.0"
proptest = "1.4.0"
rand = "0.9.2"
config = { version = "0.13.4", features = ["toml", "json", "yaml"] }
clap = { version = "4.5.3", features = ["derive"] }




[[bin]]
name = "blog_tester"

[[bin]]
name = "blog_property_test"
path = "src/blog_property_test.rs"