groups:
  - name: container_alerts
    rules:
      # Container CPU Usage Alert
      - alert: ContainerHighCPUUsage
        expr: sum by(name) (rate(container_cpu_usage_seconds_total{name!=""}[5m])) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} CPU usage is above 80% for more than 5 minutes"
          value: "{{ $value }}%"

      # Container Memory Usage Alert
      - alert: ContainerHighMemoryUsage
        expr: (container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes{name!=""} * 100) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} memory usage is above 85% for more than 5 minutes"
          value: "{{ $value }}%"

      # Container Restart Alert
      - alert: ContainerRestarting
        expr: changes(container_start_time_seconds{name!=""}[15m]) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} restarting frequently"
          description: "Container {{ $labels.name }} has restarted more than 2 times in the last 15 minutes"
          value: "{{ $value }} restarts"

      # Container Down Alert
      - alert: ContainerDown
        expr: absent(container_last_seen{name!=""})
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.name }} is down"
          description: "Container {{ $labels.name }} has been down for more than 1 minute"

      # Container Health Check Alert
      - alert: ContainerUnhealthy
        expr: container_health_status{name!=""} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.name }} is unhealthy"
          description: "Container {{ $labels.name }} health check has been failing for more than 1 minute"

      # Container High Network Traffic Alert
      - alert: ContainerHighNetworkTraffic
        expr: sum by (name) (rate(container_network_receive_bytes_total{name!=""}[5m]) + rate(container_network_transmit_bytes_total{name!=""}[5m])) / 1024 / 1024 > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High network traffic in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} network traffic is above 50 MB/s for more than 5 minutes"
          value: "{{ $value }} MB/s"

      # Container Disk Usage Alert
      - alert: ContainerHighDiskUsage
        expr: (container_fs_usage_bytes{name!=""} / container_fs_limit_bytes{name!=""} * 100) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} disk usage is above 85% for more than 5 minutes"
          value: "{{ $value }}%"

      # cAdvisor Down Alert
      - alert: CAdvisorDown
        expr: up{job="cadvisor"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "cAdvisor is down on {{ $labels.instance }}"
          description: "cAdvisor has been down for more than 1 minute on {{ $labels.instance }}"

      # Blog API Container Alert
      - alert: BlogAPIContainerDown
        expr: absent(container_last_seen{name=~".*blog-api.*"})
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Blog API container is down"
          description: "Blog API container has been down for more than 1 minute"

      # Nginx Container Alert
      - alert: NginxContainerDown
        expr: absent(container_last_seen{name=~".*nginx.*"})
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Nginx container is down"
          description: "Nginx container has been down for more than 1 minute"